### PR TITLE
wolfSSL FIPS: needs unlocking and locking of key

### PR DESCRIPTION
**Pull request by SparkiDev**

### CODE REVIEW

**Review by pabuhler — APPROVED** [review]
I will take your word on this as it is wolfssl specific

**Comment by SparkiDev** [comment]
Customer using a patched older version hit this problem.
Adding fix to main.

Anything more I need ro do before merging?

**Comment by pabuhler** [comment]
no, was going to merge today

**Comment by SparkiDev** [comment]
Thanks @pabuhler!

**Pull request merged**
