### PR TITLE
make rtp_decoder compile on MinGW

### PR DESCRIPTION
**Pull request by MoeRT09**
For several reasons the compilation of rtp_decoder fails when compiling on Windows using MinGW. This pull request fixes this.

### CODE REVIEW

**Comment by pabuhler** [comment]
Hi @MoeRT09, thanks for the patch, configure.in was just renamed to configure.ac so unfortunately you will need to reapply.  There is also an out standing issue/pr relating to pcap support, #328 & #366, that you might need to consider, I would need to look a little closer at your patch to see how it would integrate there.

**Comment by MoeRT09** [comment]
@pabuhler I tried to address your suggestions. The correct Lib(w)pcap now gets only linked to rtp_decoder.

**Comment by pabuhler** [comment]
looks like clang-format did not like your commit
https://travis-ci.org/cisco/libsrtp/jobs/296342642

could you fix it up?

thanks

**Comment by MoeRT09** [comment]
done 🙂

**Pull request merged**
