### PR TITLE
Implement fuzzers

### PR DESCRIPTION
**Pull request by guidovranken**

### CODE REVIEW

**Comment by pabuhler** [comment]
Thanks I will have some time to review next week.  Before merge we would need to fix the code format checking, If you like I can do that once the rest of the code is reviewed.

**Comment by pabuhler** [comment]
@guidovranken , I am try to build and run this locally but it is not working for me. Are you able to include some instructions on how to use the fuzzer, compile & run.

**Comment by guidovranken** [comment]
Hi Pascal,

this works:

```
git clone git@github.com:guidovranken/libsrtp.git
cd libsrtp/
git checkout fuzzing
autoreconf -ivf
CC=clang CXX=clang++ CXXFLAGS="-fsanitize=fuzzer-no-link,address,undefined -g -O3" CFLAGS="-fsanitize=fuzzer-no-link,address,undefined -g -O3" LDFLAGS="-fsanitize=fuzzer-no-link,address,undefined" ./configure
LIBFUZZER="-fsanitize=fuzzer" make srtp-fuzzer

# fuzzer/srtp-fuzzer has been created
```

**Comment by pabuhler** [comment]
@guidovranken thanks, maybe we should add the last two lines to the readme file ...

**Comment by guidovranken** [comment]
Done

**Comment by pabuhler** [comment]
@guidovranken  thanks, if you don't mind I will apply the clang format tool to this PR so it matches the rest of libSRTP code and add support in travis to build the fuzzer to ensure it does not break.

**Pull request merged**
