### PR TITLE
Remove tabs, fix typos, etc.

### PR DESCRIPTION
**Pull request by paulej**

### CODE REVIEW

**Comment by bifurcation** [comment]
Shouldn’t this just apply clang-format?

**Comment by paulej** [comment]
That might change a lot of lines. I just wanted to fix the whitespace, which doesn't look so disruptive. Also, that won't work on .md and .css files.


-------- Original Message --------

**Comment by pabuhler** [comment]
speaking of clang-format   we should probably update the version in use.

**Comment by pabuhler** [comment]
@paulej have you run clang format after making the changes to source files ?  I have added clang format as a git hub action now so if you rebase or merge from master the format check will run on this PR

**Comment by paulej** [comment]
@pabuhler No. I didn't want to create formatting changes that would look extensive. I just wanted to remove the inconsistent use of tabs.

**Pull request closed without merging**
