### PR TITLE
Don't use underscore as leading character in header guards.

### PR DESCRIPTION
**Pull request by pabuhler**
This address the concern in #114 , It still compiles both with and without opeenssl for me. Not sure if there is a platform where this will be a problem.

### CODE REVIEW

**Comment by JonathanLennox** [comment]
Might be better to use SRTP_AES_H, etc, instead?  Just to avoid the possibility of conflicts with other headers?

**Comment by pabuhler** [comment]
I was thinking the same but then should we change all includes? I see that openssl has HEADER_AES_H

**Comment by JonathanLennox** [comment]
The public headers are probably higher priority -- particularly RTP_H seems dangerously likely to conflict with other code.  But I'd be inclined to change all of them, on the same principle that led us to add srtp_ to all the public symbols.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/cisco/libsrtp/pull/242/commits/6a832d70822238af53ab04ffbf17c03fbc74d954 "Prefix public header include guards with SRTP_").

**Pull request merged**
