### PR TITLE
Remove flags incompatible with -fembed-bitcode for iOS

### PR DESCRIPTION
**Pull request by ocrete**
This simple should fix issue #411, we've been using it in the GStreamer build for a while and I just notice it hadn't been uptreamed.

### CODE REVIEW

**Comment by itollefsen** [comment]
I think you inadvertently removed `-headerpad_max_install_names` in addition to the `-undefined dynamic_lookup` flag you meant to remove.

Removing `-undefined` is fine. It defaults to `error`. I'm not sure why it was set to `dynamic_lookup`in the first place. Could be historical reasons I guess.

But we want to keep `-headerpad_max_install_names` to reserve space in the header for changing that name later to the actual install location (if necessary).

**Comment by itollefsen** [comment]
I think you inadvertently removed `-headerpad_max_install_names` in addition to the `-undefined dynamic_lookup` flag you meant to remove.

Removing `-undefined` is fine. It defaults to `error`. I'm not sure why it was set to `dynamic_lookup`in the first place. Could be historical reasons I guess.

But we want to keep `-headerpad_max_install_names` to reserve space in the header for changing that name later to the actual install location (if necessary).

**Comment by itollefsen** [comment]
I think you inadvertently removed `-headerpad_max_install_names` in addition to the `-undefined dynamic_lookup` flag you meant to remove.

Removing `-undefined` is fine. It defaults to `error`. I'm not sure why it was set to `dynamic_lookup`in the first place. Could be historical reasons I guess.

But we want to keep `-headerpad_max_install_names` to reserve space in the header for changing that name later to the actual install location (if necessary).

**Comment by pabuhler** [comment]
@ocrete  Can you confirm that removing headerpad_max_install_names was a oversight?

**Comment by ocrete** [comment]
> @ocrete Can you confirm that removing headerpad_max_install_names was a oversight?

Tbh, I don't remember. I think removing it was required for the iOS builds to succeed. But one should probably test with the latest XCode as they may have improved things.

**Comment by itollefsen** [comment]
Actually,  `-headerpad_max_install_names`  has no effect if you use `-fembed-bitcode`. Bitcode is "just" another IR representation, and it will be recompiled again for the target architecture. Hence it makes no sense to add space for binary patching. The linker will issue a warning if the two are combined. This will presumably fail if warnings are treated as errors.

If you want to submit apps to the app store today for any of the Apple platforms, you must include bitcode. Unfortunately, the current check is for whether the host platform is Darwin. That doesn't help at all in determining whether you want to embed bitcode or not.

Perhaps this could be solved by a configure option to enable bitcode? Which would then omit `-headerpad_max_install_names` etc.

**Comment by pabuhler** [comment]
This should be resolved now as part of #472, just reopen if there are still issues.

**Pull request closed without merging**
